PERSISTENCE_FOLDER = 'persistence'

PERSISTENCE_FILEPATH = 'persistence/tree.pkl'
PERSISTENCE_BACKUP_FILEPATH = 'persistence/tree_BACKUP.pkl'

PERSISTENCE_BUNDLE_FILEPATH = 'persistence/bundles.pkl'
PERSISTENCE_BUNDLE_BACKUP_FILEPATH = 'persistence/bundles_BACKUP.pkl'

DEFAULT_CONTEXT = 'dev'

RESERVED_SHEETS = ['BUNDLES', 'TREE']

SHEET_TREE_COLUMNS = ['CONTEXT', 'TREE', 'TARGET', 'NODE', 'RULE', 'TRUE', 'FALSE']

LINEBREAK = '[LINEBREAK]'
INNERLINEBREAK = '[INNERLINEBREAK]'
SEMICOLON = '[SEMICOLON]'